media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }